### ISSUE TITLE
Tables in version VPinballX_GL-10.7.1-77 are much too dark

### ISSUE THREAD

**Issue by Joey-2001** [vpinball/vpvr#3] opened 2022-05-16 14:56 UTC
I just played the version VPinballX_GL-10.7.1-77-25f7592-Release-win-x86 and with that version tables in VR werde unplayable for me, because they all are terrible dark. I add two screenshots; one with the version VPinballX_GL-10.7.1-67 and one with the VPinballX_GL-10.7.1-77.
I used both glshader-versions for both programs. But the result is the same. 10.7.1-67 is OK.
The settings are the same.
![10 7 1 67](https://user-images.githubusercontent.com/35002625/168622063-0ab89ec1-0273-4b97-bae0-5d88e52aa385.jpg)
![10 7 1 77](https://user-images.githubusercontent.com/35002625/168622070-0582cc10-48aa-4361-9383-cadaf2b4d12d.jpg)

**Comment by toxieainc** [comment] 2022-05-16 19:06
Yes, this is known, but i haven't had the time yet to track the regression down. Thanks for the report!

**Comment by Sixtoe** [comment] 2022-05-19 15:03
Confirmed and happened between -76 and -77.
I've tried all the basic things like changing between using steamvr and opencomposite, changing the RGBA 8 and Blit to 16 and Shader after seeing the RGB and gamme change notes from the previous builds).
Can't get it to look any different.
Oculus Rift S on RTX 3070.

**Comment by vbousquet** [comment] 2022-06-01 20:56
I have been testing this while implementing half float for HDR textures. My understanding of the problem is that if you run latest build without updating your glsl shader folder, you will get this dark behavior. But if you do update it (copy latest https://github.com/vpinball/vpvr/tree/master/glshader) then everything will be find.

@Joey-2001 @Sixtoe if you could test and confirm this solve it for you, I think this could be closed.

**Comment by toxieainc** [comment] 2022-06-01 22:04
This still happens. Its just that not all tables are affected.
I think that my sRGB changes caused this, but couldn't find exactly yet which part(s).

**Comment by jsm174** [comment] 2022-06-01 22:55
Looking forward to a fix for this! I'm getting further in the macos port and I have most of the react-os vbs parser / compiler "compiling".  Can you recommend a table that does work because every table I've tried is dark? That would help me rule out of I have a bug somewhere or it is this issue. 

<img width="1271" alt="Screen Shot 2022-06-01 at 6 54 50 PM" src="https://user-images.githubusercontent.com/1197137/171514837-68408e9f-af9e-432f-8085-a18746194d55.png">

**Comment by vbousquet** [comment] 2022-06-02 05:33
I use the 3 following tables for my tests:
- the blank table
- the HDR Prim test table (in the PR for HDR primitives)
- an unreleased lightmapped Twilight Zone table developped under the VPW group
I thought they did all work but I may have miss something. I will have a deeper look after work this evening

**Comment by toxieainc** [comment] 2022-06-02 05:57
Yes, at least the builtin tables all look pretty normal to me.

btw @vbousquet : Why did you change the channel order only for float textures from BGR to RGB?
(something that is also on my todo list for a while to investigate/clean up, but haven't got to it yet)

**Comment by vbousquet** [comment] 2022-06-02 06:54
I did reversed BGR to RGB for HDR texture since they were right (at least on my tests) before the SRGB change. Then in the SRGB change, both LDR and HDR texture were changed in the shader to be processed as bgr, breaking the rendering of HDR (on my tests), so I reverted this part. I did it during the texture loading (to avoid processing it in the shader) which led back to correct behavior. This is not linked to the RGB16F but a fix I made before adding it.

Now regarding the why HDR are RGB and others are BGR. Honestly, I don't know since I did not dig in the image loading code. I imagine that they do not use the same library or the same settings. This would have to be checked (and eventually changed at the loading stage, checking the impact on the editor as well).

**Comment by toxieainc** [comment] 2022-06-02 07:24
Okay, thanks, good catch!

**Comment by jsm174** [comment] 2022-06-02 10:46
@vbousquet, @toxieainc  - thanks! I just tried the blank table. Everything looks right except for the playfield wood, so I'll start digging in:

<img width="2018" alt="Screen Shot 2022-06-02 at 6 42 49 AM" src="https://user-images.githubusercontent.com/1197137/171613141-8cc6bac7-45f2-48cf-8bf4-5d5170cb4b6c.png">
 
Edit: I see blue and red on the lower left three flippers are reversed...

**Comment by vbousquet** [comment] 2022-06-02 10:54
This a RGB BGR bug. It is visible on the playfield and the flipper bats on the side. I will review the complete loading this evening. I must have been too fast on this

**Comment by jsm174** [comment] 2022-06-02 11:01
Thanks! I just looked and all the images that are wrong are jpegs. I'll step through that just to make sure it's not on my end...

**Comment by jsm174** [comment] 2022-06-02 12:09
So, this particular issue was in my port. (Sorry didn't mean to side track this thread).

Jpegs run through code where it uses `rotl`. macos didn't have it, so the code I found was incorrect.

Instead of using a macro to swap them out:

```
#ifndef __APPLE__
#define ROTL(x,y) _rotl(x,y)
#else
#include <bit>
#define ROTL(x,y) std::__rotl(x,y)
#endif
```

I found that `stb_image` has `stbi_lrot`:

```
pdst[o] = (src & 0xFF00FF00u) | stbi_lrot(src & 0x00FF00FFu, 16);
```

This seems to work. I just need to confirm on Windows.
<img width="1136" alt="Screen Shot 2022-06-02 at 8 08 30 AM" src="https://user-images.githubusercontent.com/1197137/171625968-2e50b39d-57cc-4510-a96b-85d366ad8d74.png">

**Comment by vbousquet** [comment] 2022-06-02 13:55
One thing is that there is no logging in VPX which makes debugging somewhat difficult. @toxieainc would you be ok if I add some logging using a header only library like https://github.com/gabime/spdlog (or another of your choice) ?

For examples, this would be when loading images are resized, mem allocation fails, script errors,...

**Comment by toxieainc** [comment] 2022-06-02 19:39
Would be okay, but please something simple, ideally single header only. And with close to no overhead if disabling the logging.  :)
The linked one looks a bit overkill to me for what we'll use it for.

**Comment by Joey-2001** [comment] 2022-06-03 09:52
I just test the new version VPinballX_GL-10.7.1-84-x86 with the Simpsons table and the older VPinballX_GL-10.7.1-67-x86.
But I don't change the shader folder. So both versions play with the shader vom v84.
That's the result:
VPinballX_GL-10.7.1-84-x86
![grafik](https://user-images.githubusercontent.com/35002625/171830083-5fc37656-4f6b-45de-a40c-ce5253c105e3.png)
VPinballX_GL-10.7.1-67-x86
![grafik](https://user-images.githubusercontent.com/35002625/171830145-244d47e5-aae1-465e-80d9-b6205bf2c6e3.png)

Then I try two other versions with the last shader folder from the 84.
VPinballX_GL-10.7.1-76-x86
Same result as in the 84. Table and room are too dark.
VPinballX_GL-10.7.1-68-x86
Same result as in the 67
Table and room are correct.

By my logic, the problem should be between VPX version 68 and 76.

**Comment by vbousquet** [comment] 2022-06-03 10:42
Sorry I did not report here. So I have also spend quite some time on this. I think I have identified the problem (I think it's the environment/radiance texture which is incorrectly processed regarding its gamma).

I will provide a PR soon for this. This is taking somewhat long because I think to do it cleanly, it needs to clean up the Texture class with:
- explicit content format, including color space linear/SRGB, RGBF16/32, alpha/not alpha
- consistent channel ordering (not a mix of RGB BGR to be interpreted later in other parts of the codebase)
- consistent data (i.e. RGB stored as RGB, not RGBA or RGBF16 stored as RGBF16, not RGBF32,...)

I have started and things are looking good (shorter & cleaner code, lower memory consumption, likely faster loading) but this is a larger change so this has to be looked at more carefully. I will try to finish this week-end and post back.

**Comment by Joey-2001** [comment] 2022-06-03 10:55
@vbousquet 
Sounds very good.
Do you have the chance to solve the annoying DMD-bug with the VR-versions 10.6 and 10.7?
If you don't know, what I mean:
If you play a table, which is made in 10.6 and have a DMD, you have to use the shader from the 10.6 VPinballX_GL. Otherwise you don't see the DMD.
The same happens with the 10.7 version. You have to use this shader.
So everytime you change to play a table between 10.6 and 10.7, you have to rename the shader-folder.
Or maybe it's easier, when we can use two different shader-folder for the versions.

**Comment by toxieainc** [comment] 2022-06-03 11:16
@vbousquet Good plan! Its overdue to do that. But please consider that we'll have to port this to VPX, too, then.
Also bare with me reviewing it, i will be pretty busy the next week.
Thanks a lot!

**Comment by vbousquet** [comment] 2022-06-03 11:23
Don't worry. I'm in no rush at all. And if everything is clean here, I will do the backport to VPX

**Comment by vbousquet** [comment] 2022-06-04 06:37
Here are some news. Regarding the too dark bug, I have fixed it. It is just the ColorGrade LUT which has an incorrect gamma. If you just change line 159+ of FBShader.glfx with this it will be correct:
`vec3 lut1 = FBGamma(textureLod(Texture4, vec2(x,          color.y), 0).xyz); // two lookups to blend/lerp between blue 2D regions
vec3 lut2 = FBGamma(textureLod(Texture4, vec2(x+1.0/16.0, color.y), 0).xyz);`

@Joey-2001 @jsm174 Here is the shader to be replaced in your shader directory if you want to test/check:
[FBShader.zip](https://github.com/vpinball/vpvr/files/8837156/FBShader.zip)

Now regarding the more in depth texture loading review, I have a first version working. It cleans up a lots of things. The memory consumption is also fairly lower (HDR images use twice less, RGB don't store an empty alpha channel). It has to be tested more thoroughly to be considered ready. ALso I did not optimize (yet) any of the image conversions, so it may be slower on some of them.

FInally I stumbled on a little thing: I was fairly frustrated by the slowness of the editor in VP 10.7 compared to VP 10.6. I did a check of the TreeView (I have another project where the TreeView eats up all the CPU) and identified that it uses a lot GetNextItem (which is uterly slow in the Win API, same problem I had on my other project). So removing a single (useless) call `if (m_layerTreeView.GetItemCount() == 0)` speeded up the editor a lot which is really nice.

**Comment by fuzzelhjb** [comment] 2022-06-04 06:50
Oh cool catch... Thx... Win32 UI developing is anything but fun...

Vincent Bousquet ***@***.***> schrieb am Sa., 4. Juni 2022,
08:37:

**Comment by Joey-2001** [comment] 2022-06-04 09:41
Thanks @vbousquet,
it seems, that the fix resolve the shader issue. I test ten tables, which are made with 10.7 in VR and they are all looking good.
I also play them in different VR-versions up to VPinballX_GL-10.7.1-84.
Great work.

**Comment by toxieainc** [comment] 2022-06-04 10:03
Superb! So closing this then..

**Closed as completed by toxieainc** 2022-06-04 10:03 UTC

**Comment by jsm174** [comment] 2022-06-04 11:29
@vbousquet - Thank you so much for this!!

<img width="1136" alt="Screen Shot 2022-06-04 at 7 28 19 AM" src="https://user-images.githubusercontent.com/1197137/171997030-44b2020e-0f16-4bd2-a263-df8867cd4725.png">

**Comment by toxieainc** [comment] 2022-06-04 12:51
@jsm174 Great progress! How do you manage to have such a sharp image though? For me, VPVR has a lot of issues with postprocessing offsets being off and thus i get a pretty blurry mess.

**Comment by jsm174** [comment] 2022-06-04 17:14
@toxie: TBH, I'm not sure.  I just got the code merged with your absolute latest. Only things I can think of

- `VPinballX.ini` has hardly anything in it since its generated
- bare minimum shader changes  (https://github.com/jsm174/vpvr/tree/feature/macos_backup/glshader_osx)
- reduce to 410
- I don't have `GL_ARB_conservative_depth` or `GL_ARB_texture_query_levels`, but I found I have `GL_ARB_texture_query_lod` and `GLAD_GL_ARB_texture_storage` (so now I can use `glTexStorage2D`)

Other than that, `RenderDevice` and `Texture` are identical.

**Comment by toxieainc** [comment] 2022-06-04 19:09
Hmmm.. Will check that, thanks for the explanations.. For me it looks pretty horrible, but i simply assumed this to be true for everybody (except the main VR use case of course)..
