### ISSUE TITLE
v323 lag issues and strobe on Flinstones table

### ISSUE THREAD

**Issue by psiomicron** [vpinball/vpvr#81] opened 2022-10-19 00:26 UTC
So far great job on getting this looking great! However, for v323 when playing the flintstones table and hitting the skill shot black circles (squares?) appear on both side of the table (possible from a strobe light). Also the table is laggy. Most other tables I have tested with this version doesn't have any lag (fyi I have a rtx 3080).

Thanks so far for all you have done!

**Comment by Joey-2001** [comment] 2022-10-19 13:44
I can agree with psiomicron. The latest version plays the tables very well. The reflections could be a bit more subtle for my taste. The playfield looks like it is made of glass. But it doesn't bother me much.
I can confirm the sharp rectangles that psiomicron mentions.
They can be seen in the video at second 55.
I also see flickering black rectangles in the area of the lockdown bar and the apron from time to time. It depends on how I move my head. I have also noticed these rectangles on another table.
I cannot detect a lag with version 323. All tested tables run cleanly without stuttering.
So great work and a big thanks.
Here are my settings and the short video.

![grafik](https://user-images.githubusercontent.com/35002625/196706261-d18f19fa-3879-4329-9bd8-1520d78afaf5.png)
![grafik](https://user-images.githubusercontent.com/35002625/196706324-19471e9c-786d-42fc-b32e-04c8895c10d4.png)
https://www.youtube.com/watch?v=wbeW4jIPwxQ

**Comment by studlygoorite** [comment] 2022-10-19 18:04
v332 has fixed the black boxes issue I/we were seeing with my setup

**Comment by vbousquet** [comment] 2022-10-19 18:15
I will close the issue then as the performance will be evaluated at the end of the merge with VPX

**Closed as completed by vbousquet** 2022-10-19 18:15 UTC
