### ISSUE TITLE
v266 testing

### ISSUE THREAD

**Issue by Joey-2001** [vpinball/vpvr#60] opened 2022-09-26 14:27 UTC
I tested the new v266 with these tables:
Cirqus Voltaire (Bally 1997) Sixtoe 1.11 - works, I edited the lighting, but that is table relevant
Flash Gordon (Bally 1981) rothbauerw 2.0 - works
Swords of Fury (Williams 1988) Bord 1.0.1 - works
Solar Fire (Williams 1981) UnclePaulie 2.0.5 - works
Red & Ted's Road Show (Williams 1994) VPinWorkshop 1.3.1 - works
Pharaoh (Williams 1981) UnclePaulie 2.0.1 - works, but the inserts looks very bad (see picture), the lightning issue from v262 is gone
Batman The Dark Knight (Stern 2008) bord 1.0.7 - doesn't work, a few seconds a black window opens, than the table crashes. The same happened in v262. I attach the crash.txt.
Capt. Fantastic and The Brown Dirt Cowboy (Bally 1976) leojreimroc 2.0 - works
Flicker (Bally 1974) Scottacus 2.06 - works
![pharaoh](https://user-images.githubusercontent.com/35002625/192302125-2f7ab639-8af5-4796-bdb8-552ccd7c6fe6.png)
[crash.txt](https://github.com/vpinball/vpvr/files/9647073/crash.txt)

**Comment by vbousquet** [comment] 2022-09-26 15:13
For Batman, it may be table related. Did you try to restart it afterward and did it worked ? Did you have the provided NVRam in your nv ram dir ?

For Pharaoh, I must look in more details since it is likely related to teh differences regarding depth buffer. Thanks!

**Comment by Joey-2001** [comment] 2022-09-26 15:38
I always close vpx after testing one table. Batman always crashes. Other user report the same in the thread at VPU.
 And I use the provided nvram.
The version 1.0.1 of Bord's Batman works.

**Comment by studlygoorite** [comment] 2022-09-26 16:44
I cannot get the updated Batman 1.0.7 to work on v144 or v266, I can get the previous version to work with both but I have a very dark backglass on every version I tested. I have the nvram file installed.

**Comment by vbousquet** [comment] 2022-09-26 17:23
Just to be sure, are you using the x86 version (Stern SAM & Whitestar II do not work with x64 version) ? Nevermind, I checked the crash log and it's x86. Strangely, I can't reproduce this one. Investigating...

**Comment by Joey-2001** [comment] 2022-09-27 07:18
Yes, I never use x64 till now. All programs are x86.

**Comment by studlygoorite** [comment] 2022-09-30 00:56
FYI, I did some more testing and pup packs still have issues with v278, not so bad with v268 and better with v266. Is there a change from v266 to v268 that may have affected this and maybe got worse with v278? Still waiting for others to confirm or deny any of this in the VR Discord but this is what I have found.

 I went through it again, pups are working with v266, then with v268 some stop working and then v278 none work that I tested. Pups I tested are AC/DC, Avatar, Star Trek Enterprise and Star Wars.....

**Comment by studlygoorite** [comment] 2022-10-04 23:39
Just tried v281 and tables with pup packs, most of them, are crashing VPVR such that I have to go into task manager and kill two pup services. Also something new that started a couple/three builds ago for me is when a pup pack crashes the VR Preview window on the desktop (that is no longer the full screen but just a small box) turns black and at the top of the box it says "XRS Debug Window:[y]: NV12/RGB [p]:ppm/png [m]: 1:1 resolution".....and a bunch more :) Update, this message at the top of the VR Preview Screen is an Oculus/Meta issue as it's there before I launch VPVR, sorry about that :)

**Comment by studlygoorite** [comment] 2022-10-12 01:54
FYI, v266 still remains as the go to for me as I just tested v287 and most tables with pup packs still crash.

**Comment by vbousquet** [comment] 2022-10-17 06:23
I moved the individual feature issue to dedicated issues for easier tracking:
- PupPack: https://github.com/vpinball/vpvr/issues/76
- Pharaoh inserts: https://github.com/vpinball/vpvr/issues/75

I will close this issue for now

**Closed as completed by vbousquet** 2022-10-17 06:23 UTC
